### ISSUE TITLE
dataset not found

### ISSUE THREAD

**Issue by hhhhpaaa** [JiyaWang/PPGNN#1]
Amazing work. There is an issue with the code runtime `from dataset import load_nc_dataset`. And I didn't find `dataset.py` in the repository, I think this one should be your custom. While it's not difficult to rewrite a `dataload`, please upload a `dataset.py` for easy reproduction.

**Comment by JiyaWang** [comment]
I'm sorry for the late reply. I have uploaded the `dataset.py`.
